#ifndef OTA_OTA_STATE_H_
#define OTA_OTA_STATE_H_

typedef enum{
	OTA_IDLE,
	OTA_HANDSHAKE,
	OTA_RECIEVE_DATA,
	OTA_VERIFY_HASH,
	OTA_WRITE_TO_FLASH,
	OTA_ERROR,
	OTA_WRITE_COMPLETE
}OTA_STATE;

#endif /* OTA_OTA_STATE_H_ */
